const courses: CourseData[] = [
  {
    id: 0,
    level: 'flash',
    lives: 3,
    maxDifficulty: 2,
    minDifficulty: 1,
    type: 'tutorial',
  },
  {
    id: 1,
    level: 'path',
    lives: 3,
    maxDifficulty: 10,
    minDifficulty: 1,
    type: 'tutorial',
  },
  {
    id: 2,
    level: 'fake flash',
    lives: 3,
    maxDifficulty: 10,
    minDifficulty: 1,
    type: 'tutorial',
  },
  {
    id: 3,
    level: 'multiflash',
    lives: 3,
    maxDifficulty: 10,
    minDifficulty: 1,
    type: 'tutorial',
  },
  {
    id: 4,
    level: 'rotate',
    lives: 3,
    maxDifficulty: 10,
    minDifficulty: 1,
    type: 'tutorial',
  },
  {
    id: 5,
    level: 'reflect',
    lives: 3,
    maxDifficulty: 10,
    minDifficulty: 1,
    type: 'tutorial',
  },
  {
    id: 6,
    level: 'x-reflect',
    lives: 3,
    maxDifficulty: 10,
    minDifficulty: 1,
    type: 'tutorial',
  },
];

export default courses;
